[project]
name = 'froggy-marketplace'
description = 'Froggy NFT Marketplace for Anibal'
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'SP3D6PV2ACBPEKYJTCMH7HEN02KP87QSP8KTEH335.commission-trait'
[contracts.custodial-marketplace]
path = 'contracts/custodial-marketplace.clar'
clarity_version = 4
epoch = 3.3

[contracts.froggy-gamma-nft]
path = 'contracts/froggy-gamma-nft.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = [
    'check_checker',
    'call_checker',
]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = true
api_url = 'https://api.hiro.so'
